namespace ETimeSheet.Application.Models.Entities;

/// <summary>
/// One status change on a submitted timesheet, mapped onto the existing
/// <c>dbo.TimeSheetSubmissionAuditLog</c> table. This is a persistence/domain
/// model and is never returned from a controller.
/// <para>
/// Every column is NOT NULL. It does not derive from <c>AuditableEntity</c>: the
/// table has no soft-delete or update columns.
/// </para>
/// </summary>
public class TimeSheetSubmissionAuditLog
{
    /// <summary>
    /// Primary key - an IDENTITY sequence number generated by the database,
    /// never supplied by the API and never repeated.
    /// </summary>
    public int TimeSheetSubmissionAuditLogId { get; set; }

    /// <summary>
    /// The sheet code the change belongs to - the same value as
    /// <c>dbo.TimesheetSubmission.Timesheetcode</c> and
    /// <c>dbo.TimeLog.SheetCode</c>. <c>varchar(20)</c>, despite the "ID" in its
    /// name.
    /// </summary>
    public string TimeSheetSubmissionId { get; set; } = string.Empty;

    /// <summary>The status the submission moved to.</summary>
    public int StatusId { get; set; }

    /// <summary>The user who made the change.</summary>
    public int CreatedBy { get; set; }

    /// <summary>When the change was made. <c>datetime</c>.</summary>
    public DateTime CreateDate { get; set; }
}
