using System.Globalization;
using ETimeSheet.Application.Interfaces.Repositories;
using ETimeSheet.Application.Models;
using ETimeSheet.Application.Models.Entities;
using ETimeSheet.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace ETimeSheet.Infrastructure.Repositories;

/// <summary>
/// Entity Framework Core data access over the existing <c>dbo.EmailQueue</c> table.
/// </summary>
public class EmailQueueRepository : IEmailQueueRepository
{
    private readonly Context _db;

    public EmailQueueRepository(Context db)
    {
        _db = db;
    }

    public async Task AddRangeAsync(
        IReadOnlyCollection<EmailQueue> emails,
        CancellationToken cancellationToken = default)
    {
        // AddRange, not AddRangeAsync: the key is an IDENTITY generated by the
        // insert. One SaveChanges - one transaction, batched INSERTs.
        _db.EmailQueue.AddRange(emails);
        await _db.SaveChangesAsync(cancellationToken);
    }

    public async Task<IReadOnlyList<EmailQueue>> GetForUpdateByUserIdAsync(
        int userId,
        IReadOnlyCollection<byte> statuses,
        CancellationToken cancellationToken = default) =>
        // Tracked deliberately, and not saved here: the caller changes these
        // rows and the request's next SaveChanges writes them, together with
        // the change that caused it.
        await _db.EmailQueue
            .Where(email => email.UserId == userId && statuses.Contains(email.EmailStatusId))
            .ToListAsync(cancellationToken);

    public async Task<IReadOnlyList<QueuedEmail>> GetQueuedSinceAsync(
        int emailTypeId,
        IReadOnlyCollection<int> userIds,
        DateTime sinceUtc,
        CancellationToken cancellationToken = default)
    {
        // CreatedDate is filled by GETDATE() - the database server's local
        // time - so the cut-off is moved onto that clock for the query, and
        // the results are moved back to UTC.
        var serverOffset = await GetServerUtcOffsetAsync(cancellationToken);
        var sinceServerTime = DateTime.SpecifyKind(sinceUtc, DateTimeKind.Unspecified) + serverOffset;

        var queued = await _db.EmailQueue
            .AsNoTracking()
            .Where(email => email.EmailTypeId == emailTypeId
                && email.UserId != null
                && userIds.Contains(email.UserId.Value)
                && email.CreatedDate >= sinceServerTime)
            .Select(email => new { email.UserId, email.CreatedDate })
            .ToListAsync(cancellationToken);

        return queued
            .Select(email => new QueuedEmail(
                email.UserId!.Value,
                DateTime.SpecifyKind(email.CreatedDate - serverOffset, DateTimeKind.Utc)))
            .ToList();
    }

    /// <summary>
    /// Read as <c>DATEPART(TZOFFSET, SYSDATETIMEOFFSET())</c>.
    /// <para>
    /// Run on the context's own connection, inside the execution strategy so
    /// the configured retry policy still covers it - as
    /// <c>TimeLogRepository</c> runs <c>spc_GetUsersTaskList</c>.
    /// </para>
    /// </summary>
    public async Task<TimeSpan> GetServerUtcOffsetAsync(CancellationToken cancellationToken = default)
    {
        var strategy = _db.Database.CreateExecutionStrategy();

        return await strategy.ExecuteAsync(async () =>
        {
            var connection = _db.Database.GetDbConnection();
            await _db.Database.OpenConnectionAsync(cancellationToken);

            try
            {
                await using var command = connection.CreateCommand();
                command.CommandText = "SELECT DATEPART(TZOFFSET, SYSDATETIMEOFFSET());";

                var minutes = Convert.ToInt32(
                    await command.ExecuteScalarAsync(cancellationToken),
                    CultureInfo.InvariantCulture);

                return TimeSpan.FromMinutes(minutes);
            }
            finally
            {
                await _db.Database.CloseConnectionAsync();
            }
        });
    }

    public async Task<IReadOnlyList<EmailQueue>> GetSendableAsync(
        IReadOnlyCollection<byte> statuses,
        int maxAttempts,
        IReadOnlyCollection<int> emailTypeIds,
        CancellationToken cancellationToken = default) =>
        // Tracked: the caller records each send's outcome on the row and saves
        // it straight away, one email at a time.
        await _db.EmailQueue
            .Where(email => statuses.Contains(email.EmailStatusId)
                && email.AttemptCount < maxAttempts
                && emailTypeIds.Contains(email.EmailTypeId))
            .OrderBy(email => email.EmailQueueId)
            .ToListAsync(cancellationToken);

    public async Task UpdateAsync(
        EmailQueue email,
        CancellationToken cancellationToken = default)
    {
        if (_db.Entry(email).State == EntityState.Detached)
        {
            _db.EmailQueue.Update(email);
        }

        await _db.SaveChangesAsync(cancellationToken);
    }
}
