using ETimeSheet.Application.Interfaces.Repositories;
using ETimeSheet.Application.Models;
using ETimeSheet.Application.Models.Entities;
using ETimeSheet.Infrastructure.Data;
using ETimeSheet.Shared.Enums;
using Microsoft.EntityFrameworkCore;

namespace ETimeSheet.Infrastructure.Repositories;

/// <summary>
/// Entity Framework Core data access over the existing
/// <c>dbo.TimesheetSubmission</c> and <c>dbo.TimeSheetSubmissionAuditLog</c>
/// tables.
/// </summary>
public class SheetSubmissionRepository : ISheetSubmissionRepository
{
    private readonly Context _db;

    public SheetSubmissionRepository(Context db)
    {
        _db = db;
    }

    public async Task<bool> ExistsAsync(
        string sheetCode,
        CancellationToken cancellationToken = default) =>
        await _db.TimesheetSubmission
            .AnyAsync(submission => submission.Timesheetcode == sheetCode, cancellationToken);

    public async Task<int?> GetSavedMinutesAsync(
        string sheetCode,
        int userId,
        CancellationToken cancellationToken = default) =>
        // Summed in SQL Server, not in memory. Days * 1440 plus the minute
        // difference between the two times is exactly the procedures'
        // DATEDIFF(MINUTE, StartDate + StartTime, EndDate + EndTime), written in
        // a form EF Core can translate. The global query filter already drops
        // soft-deleted entries.
        //
        // GroupBy on a constant makes an empty match come back as no row -
        // null - rather than as a SUM of 0, so the caller can tell "nothing
        // saved on this sheet" from "entries totalling zero".
        await _db.TimeLog
            .Where(timeLog => timeLog.SheetCode == sheetCode
                && timeLog.UserId == userId
                && timeLog.Status == TimeLogStatus.Save
                && timeLog.StartDate != null
                && timeLog.StartTime != null
                && timeLog.EndDate != null
                && timeLog.EndTime != null)
            .GroupBy(_ => 1)
            .Select(entries => entries.Sum(timeLog =>
                EF.Functions.DateDiffDay(timeLog.StartDate, timeLog.EndDate) * 1440
                + EF.Functions.DateDiffMinute(timeLog.StartTime, timeLog.EndTime)))
            .FirstOrDefaultAsync(cancellationToken);

    public async Task<TimesheetSubmission> AddAsync(
        TimesheetSubmission submission,
        CancellationToken cancellationToken = default)
    {
        await _db.TimesheetSubmission.AddAsync(submission, cancellationToken);

        // Also writes any audit entry staged by AddAuditLog - one SaveChanges,
        // one transaction.
        await _db.SaveChangesAsync(cancellationToken);
        return submission;
    }

    public async Task<TimesheetSubmission?> GetForUpdateAsync(
        string sheetCode,
        CancellationToken cancellationToken = default) =>
        // Tracked deliberately: the caller mutates this instance and the change
        // tracker turns those mutations into an UPDATE of just those columns.
        await _db.TimesheetSubmission
            .FirstOrDefaultAsync(submission => submission.Timesheetcode == sheetCode, cancellationToken);

    public async Task UpdateAsync(
        TimesheetSubmission submission,
        CancellationToken cancellationToken = default)
    {
        // As AdminRepository.UpdateAsync: Update() only for a detached
        // instance, so a tracked one writes only the columns that changed.
        if (_db.Entry(submission).State == EntityState.Detached)
        {
            _db.TimesheetSubmission.Update(submission);
        }

        // Also writes any audit entry staged by AddAuditLog - one SaveChanges,
        // one transaction.
        await _db.SaveChangesAsync(cancellationToken);
    }

    // Add, not AddAsync: AddAsync exists only for value generators that hit the
    // database, and an IDENTITY key is generated by the insert itself.
    public void AddAuditLog(TimeSheetSubmissionAuditLog auditLog) =>
        _db.TimeSheetSubmissionAuditLog.Add(auditLog);

    public async Task<IReadOnlyList<SubmittedSheetDetail>> GetSubmittedSheetListAsync(
        int adminId,
        int userId,
        int orgId,
        CancellationToken cancellationToken = default) =>
        // The interpolated holes become SqlParameters, never concatenated SQL.
        // The procedure orders the rows, so nothing is re-sorted here.
        await _db.spc_GetSubmittedSheetList
            .FromSqlInterpolated($"EXEC dbo.spc_GetSubmittedSheetList @PAdminID = {adminId}, @PUserID = {userId}, @POrgID = {orgId}")
            .ToListAsync(cancellationToken);
}
