/*
    THE TIMELOG MODULE'S MODEL - one file, every shape the module exchanges.

    TimeLogController and TimeLogService have exactly one model file between
    them, and this is it: the request payloads, the response payloads, and the
    rows the module's stored procedures return. Adding a shape to this module
    means adding a class HERE, not adding a file next to it.

    A module may READ another module's model - TimeLogService reads the Admin
    entity, for instance - but it never gains a second model file of its own.

    Not here, deliberately:
      - EF entities (Models/Entities/) map one-to-one to a TABLE, not to a
        controller. dbo.DayMaster belongs to no controller at all, and
        dbo.TimesheetMasterSetup is read by two of them.
      - Validators, mappings and services keep their own files; this is the
        model, not the module.

    ORDER MATTERS in the response types. System.Text.Json writes properties in
    declaration order, so moving a property up or down here changes the JSON a
    client receives. Reordering is a contract change, not a tidy-up.
*/

using ETimeSheet.Shared.Enums;

namespace ETimeSheet.Application.Models;

/// <summary>
/// Body of the "log my time" request - one block of work an employee recorded
/// against one task.
/// <para>
/// <b>Adds or edits.</b> With <see cref="TimeLogId"/> left out or zero, a new
/// entry is created. With the id of an existing entry, that entry is
/// overwritten with this payload, under the same rules as a new one - plus the
/// rule that the entry as it stands must still be open to change.
/// </para>
/// <para>
/// <c>UserId</c> is supplied by the caller and would normally come from the
/// authenticated principal. Authentication is switched off for this project for
/// now, so it travels in the payload - deliberately temporary, exactly as on the
/// read endpoints.
/// </para>
/// </summary>
public class TimeLogSaveRequest
{
    /// <summary>
    /// The entry to edit - its <c>SheetID</c>, the <c>sheetId</c> a save
    /// returns. Zero or left out creates a new entry instead.
    /// </summary>
    public int TimeLogId { get; set; }

    /// <summary>The employee the time belongs to. Required - it is also what selects the timesheet setup the entry is validated against.</summary>
    public int UserId { get; set; }

    /// <summary>The task the work was done on. Required.</summary>
    public int TaskId { get; set; }

    /// <summary>
    /// <c>true</c> when <see cref="TaskId"/> is a project task, <c>false</c>
    /// when it is a sprint task - the two lists
    /// <c>get-user-task-list-by-userid</c> returns, whose ids can coincide.
    /// <b>Required.</b> Nullable here only so that a missing value can be told
    /// apart from <c>false</c> and refused - a plain <c>bool</c> would bind an
    /// omitted field as <c>false</c> and silently call every such task a
    /// sprint task.
    /// </summary>
    public bool? IsProjectTask { get; set; }

    /// <summary>What was worked on. Optional, and unbounded - the column is <c>nvarchar(max)</c>.</summary>
    public string? Description { get; set; }

    // SheetCode is deliberately NOT here. It is generated by TimeLogService -
    // SHT0001, SHT0002, ... - once per user per timesheet week, and comes back on
    // TimeLogResponse. A caller
    // that could supply one could collide with the sequence or skip a number,
    // and then no reader could trust the codes to mean anything.

    /// <summary>
    /// The day the work started. A calendar date - the column is <c>date</c>, so
    /// any time part is ignored.
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>
    /// The day the work ended. Optional: left out it is the same day as
    /// <see cref="StartDate"/>, which is the ordinary case. It exists for a
    /// shift that runs past midnight, which is the only reason the table carries
    /// two dates.
    /// </summary>
    public DateTime? EndDate { get; set; }

    /// <summary>
    /// Clock time the work started, as a string in <c>hh:mm:ss</c> - for example
    /// <c>"09:00:00"</c>. Required.
    /// <para>
    /// A string rather than a <c>TimeSpan</c>, as on every time input in this API:
    /// the contract is one exact format, and <c>TimeLogService</c> is what reads
    /// it. See <see cref="ETimeSheet.Shared.Utilities.TimeOfDay"/>.
    /// </para>
    /// </summary>
    public string? StartTime { get; set; }

    /// <summary>
    /// Clock time the work ended, also <c>hh:mm:ss</c>. Required, and must be
    /// after the start once both dates are taken into account.
    /// </summary>
    public string? EndTime { get; set; }

    /// <summary>
    /// <b>1 = Save, 2 = Draft.</b> Required - an entry with no status is neither
    /// saved nor drafted, and the reads would not know what to do with it.
    /// </summary>
    public TimeLogStatus Status { get; set; }

    /// <summary>
    /// The user recording the entry. Usually the same person as
    /// <see cref="UserId"/>, but not necessarily - a manager may log on someone's
    /// behalf, and the row should say who actually did it. Written to
    /// <c>CreatedBy</c> on an add and to <c>UpdatedBy</c> on an edit; an edit
    /// never changes who created the entry.
    /// <para>
    /// <b>Temporary</b>, as on <c>AdminSaveRequest.CreatedBy</c>: this
    /// belongs in the token, and it moves there the moment JWT is switched back
    /// on.
    /// </para>
    /// </summary>
    public int CreatedBy { get; set; }
}

/// <summary>
/// Caller-facing view of one row returned by
/// <c>spc_GetTimeLoggedDetailsForTask</c>.
/// </summary>
public class TimeLoggedDetailResponse
{
    public int SheetId { get; init; }

    public string? SheetCode { get; init; }

    /// <summary>The task the entry is logged against. Null on a row with no task.</summary>
    public int? TaskId { get; init; }

    /// <summary>Whether the task is a project task. Null on rows written before the column existed.</summary>
    public bool? IsProjectTask { get; init; }

    public string? Description { get; init; }

    public DateTime? StartDate { get; init; }

    public TimeSpan? StartTime { get; init; }

    public DateTime? EndDate { get; init; }

    public TimeSpan? EndTime { get; init; }

    /// <summary>
    /// <b>1 = Save, 2 = Draft only</b> - see
    /// <see cref="ETimeSheet.Shared.Utilities.Constants.TimeLog.Status"/>.
    /// Serialised by name, so a caller sees "Save" or "Draft".
    /// </summary>
    public TimeLogStatus? Status { get; init; }

    /// <summary>"Save" or "Draft". Empty when the row's <c>Status</c> column is null.</summary>
    public string StatusName { get; init; } = string.Empty;

    /// <summary>Duration of this entry in hours, to two decimal places.</summary>
    public decimal? TotalWorkingHours { get; init; }

    /// <summary>Duration of this entry in whole minutes.</summary>
    public int? TotalWorkingMinutes { get; init; }
}

/// <summary>
/// One row of <c>dbo.TimeLog</c> as the API returns it - the entry exactly as it
/// was stored, so a caller that has just logged time can show it back without a
/// second request.
/// <para>
/// Distinct from <see cref="TimeLoggedDetailResponse"/>, which is the shape
/// <c>spc_GetTimeLoggedDetailsForTask</c> returns. They overlap but are not the
/// same thing, and tying the write response to the procedure's shape would make
/// the procedure impossible to change.
/// </para>
/// </summary>
public class TimeLogResponse
{
    /// <summary>The generated key. This is the one field the caller could not have known before the call.</summary>
    public int SheetId { get; set; }

    public string? SheetCode { get; set; }

    public int? TaskId { get; set; }

    /// <summary>Whether the task is a project task. Null on rows written before the column existed.</summary>
    public bool? IsProjectTask { get; set; }

    public string? Description { get; set; }

    public int? UserId { get; set; }

    public DateTime? StartDate { get; set; }

    public TimeSpan? StartTime { get; set; }

    public DateTime? EndDate { get; set; }

    public TimeSpan? EndTime { get; set; }

    /// <summary>1 = Save, 2 = Draft.</summary>
    public TimeLogStatus? Status { get; set; }

    /// <summary>The status spelled out, so a client does not have to carry the numbers.</summary>
    public string StatusName { get; set; } = string.Empty;

    /// <summary>
    /// How long the entry covers, in hours to two places. Computed from both
    /// ends including their dates, so an overnight entry measures correctly
    /// rather than coming out negative.
    /// </summary>
    public decimal TotalWorkingHours { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreateDate { get; set; }

    /// <summary>Who last edited the entry. Null until it has been edited.</summary>
    public int? UpdatedBy { get; set; }

    /// <summary>When the entry was last edited, UTC. Null until it has been edited.</summary>
    public DateTime? UpdateDate { get; set; }
}

/// <summary>
/// Caller-facing view of a user's timesheet setup, as returned by
/// <c>spc_GetTimesheetMasterSetupByUserID</c>.
/// </summary>
public class TimesheetMasterSetupResponse
{
    public int SetupId { get; init; }

    /// <summary>
    /// From the <c>MaxTimeinhrs</c> column, a <c>time(7)</c>. Serialises as
    /// <c>"08:00:00"</c>, not as a number.
    /// </summary>
    public TimeSpan? MaxTimeLoggedByUserInHours { get; init; }

    /// <summary>From the <c>MaxTiminmins</c> column, a <c>time(7)</c>.</summary>
    public TimeSpan? MaxTimeLoggedByUserInMinutes { get; init; }

    public int? ContractType { get; init; }

    /// <summary>
    /// First day of the timesheet week - a <c>DayMaster.DayID</c>: 1 = Monday
    /// through 7 = Sunday. It was a two-character code until 2026-09-17.
    /// </summary>
    public int? StartDay { get; init; }

    /// <summary>Last day of the timesheet week. A <c>DayMaster.DayID</c>, as <see cref="StartDay"/>.</summary>
    public int? EndDay { get; init; }

    /// <summary>
    /// Whether the user may log time against a previous day. Held as 0 or 1 in
    /// the database and surfaced as <c>true</c>/<c>false</c>.
    /// <para>
    /// The procedure derives this from the database server's clock, not the
    /// employee's - see the note on <c>TimesheetMasterSetupDetail</c>.
    /// </para>
    /// </summary>
    public bool? CanUserLoggedPreDayTime { get; init; }

    /// <summary>The user's country, from <c>dbo.Signup.CountryID</c>.</summary>
    public int? CountryId { get; init; }

    /// <summary>
    /// The IANA time zone this user's timesheet day is measured in - one id,
    /// such as <c>"Asia/Kolkata"</c>. Null for a setup saved before time zones
    /// existed, in which case the API falls back to UTC.
    /// </summary>
    public string? TimeZone { get; init; }
}

/// <summary>
/// One task in <see cref="UserTaskListResponse"/> - an id and a name, whether
/// it is a project task or a sprint task.
/// <para>
/// The id is only unique <b>within its own list</b>. A project task's
/// <c>TaskId</c> is a <c>dbo.TaskMaster.TaskID</c> and a sprint task's is a
/// <c>dbo.SprintTaskManagement.SprintTaskID</c>, so the same number can
/// appear in both lists and mean two different tasks.
/// </para>
/// </summary>
public class UserTaskResponse
{
    public int TaskId { get; init; }

    public string? TaskName { get; init; }
}

/// <summary>
/// What the user task list endpoint returns: the tasks one user owns, split
/// the way <c>spc_GetUsersTaskList</c> splits them. Both lists are always
/// present, and empty rather than null when the user owns none.
/// </summary>
public class UserTaskListResponse
{
    public IReadOnlyCollection<UserTaskResponse> ProjectTasks { get; init; } =
        Array.Empty<UserTaskResponse>();

    public IReadOnlyCollection<UserTaskResponse> SprintTasks { get; init; } =
        Array.Empty<UserTaskResponse>();
}

/// <summary>
/// What the user dashboard summary endpoint returns: one user's logged time
/// today and this timesheet week, measured against what their setup expects.
/// <para>
/// Every duration comes twice - whole minutes for sums and charts, and text
/// such as <c>"7h 30m"</c> for display. The expected, percentage and pending
/// figures are <see langword="null"/> when the user has no setup (or an
/// incomplete one): there is nothing to measure against, which is not 0%.
/// </para>
/// </summary>
public class UserDashboardSummaryResponse
{
    public int UserId { get; init; }

    public string? Name { get; init; }

    /// <summary>First day of the current timesheet week, anchored on the setup's <c>StartDay</c> (Monday when none).</summary>
    public DateTime WeekStartDate { get; init; }

    /// <summary>Last day of the current timesheet week - always six days after <see cref="WeekStartDate"/>.</summary>
    public DateTime WeekEndDate { get; init; }

    public int TodayLoggedMinutes { get; init; }

    public string? TodayLoggedText { get; init; }

    public int WeekLoggedMinutes { get; init; }

    public string? WeekLoggedText { get; init; }

    public int? WeekExpectedMinutes { get; init; }

    public string? WeekExpectedText { get; init; }

    /// <summary>Logged as a percentage of expected, two decimals, capped at 100.</summary>
    public decimal? WeekLoggedPercentage { get; init; }

    /// <summary>Expected minus logged, never below zero.</summary>
    public int? WeekPendingMinutes { get; init; }

    public string? WeekPendingText { get; init; }
}

/// <summary>
/// One row of the result set returned by <c>dbo.spc_GetTimeLoggedDetailsForTask</c>.
/// <para>
/// This is a keyless type: it is not a table, it has no identity and it is never
/// tracked or written. It exists solely to give the procedure's SELECT list a
/// shape EF Core can materialise, which is why it carries exactly the twelve
/// columns the procedure returns - no more.
/// </para>
/// </summary>
public class TimeLoggedDetail
{
    public int SheetId { get; set; }

    public string? SheetCode { get; set; }

    public string? Description { get; set; }

    public DateTime? StartDate { get; set; }

    public TimeSpan? StartTime { get; set; }

    public DateTime? EndDate { get; set; }

    public TimeSpan? EndTime { get; set; }

    /// <summary>
    /// The <c>Status</c> column as returned by the procedure.
    /// <para><b>1 = Save, 2 = Draft only</b> - see
    /// <see cref="ETimeSheet.Shared.Utilities.Constants.TimeLog.Status"/>.</para>
    /// </summary>
    public TimeLogStatus? Status { get; set; }

    /// <summary>
    /// Duration of this entry in hours, computed by the procedure and already
    /// rounded to two decimal places. <c>DATEDIFF(...)/60.0</c> yields a SQL
    /// <c>numeric</c>, hence <c>decimal</c> rather than <c>double</c>.
    /// </summary>
    public decimal? TotalWorkingHours { get; set; }

    /// <summary>
    /// Duration of this entry in whole minutes, computed by the procedure.
    /// <c>DATEDIFF</c> returns an <c>int</c>, and this is the exact value the
    /// summary totals are built from.
    /// </summary>
    public int? TotalWorkingMinutes { get; set; }

    /// <summary>The <c>TaskID</c> column - returned by the procedure since 2026-09-25.</summary>
    public int? TaskId { get; set; }

    /// <summary>
    /// The <c>IsProjectTask</c> column, a nullable <c>bit</c> - added to the
    /// procedure on 2026-09-24. Null on rows written before the column existed.
    /// </summary>
    public bool? IsProjectTask { get; set; }
}

/// <summary>
/// One row of the result set returned by
/// <c>dbo.spc_GetTimesheetMasterSetupByUserID</c> - the limits and working-week
/// settings that apply to one user's timesheets.
/// <para>
/// This is a keyless type: it is not a table, it has no identity and it is never
/// tracked or written. It exists solely to give the procedure's SELECT list a
/// shape EF Core can materialise, which is why it carries only the six columns
/// the procedure returns. The full table is
/// <see cref="ETimeSheet.Application.Models.Entities.TimesheetMasterSetup"/>.
/// </para>
/// </summary>
public class TimesheetMasterSetupDetail
{
    public int SetupId { get; set; }

    /// <summary>
    /// The <c>MaxTimeinhrs</c> column, aliased by the procedure. A
    /// <c>time(7)</c>, not a number - so "8 hours" is stored as <c>08:00:00</c>.
    /// </summary>
    public TimeSpan? MaxTimeLoggedByUserInHours { get; set; }

    /// <summary>The <c>MaxTiminmins</c> column, aliased by the procedure. Also a <c>time(7)</c>.</summary>
    public TimeSpan? MaxTimeLoggedByUserInMinutes { get; set; }

    public int? ContractType { get; set; }

    /// <summary>
    /// First day of the timesheet week - a <c>dbo.DayMaster.DayID</c> (1 = Monday
    /// ... 7 = Sunday). The procedure selects the column straight through, so it
    /// returns whatever type the column has: an <c>int</c> since 2026-09-17.
    /// </summary>
    public int? StartDay { get; set; }

    /// <summary>Last day of the timesheet week. A <c>DayMaster.DayID</c>, as <see cref="StartDay"/>.</summary>
    public int? EndDay { get; set; }

    /// <summary>
    /// Whether the user may log time against a previous day. Stored as 0 or 1.
    /// <para>
    /// Exposed as a <c>bool?</c> rather than a number so callers get
    /// <c>true</c>/<c>false</c> instead of having to know that 1 means yes. The
    /// store type is handled in the mapping, not here.
    /// </para>
    /// <para>
    /// <b>Derived by the procedure from the SQL Server's own clock</b> - it
    /// compares <c>CAST(GETDATE() AS TIME)</c> against <c>TimeEntryLockAt</c> -
    /// so it answers "has the cut-off passed <i>here</i>", not "has it passed
    /// where the employee is". It is also 0 when <c>TimeEntryLockAt</c> is
    /// null. <c>TimeLogService</c> does not read it: the save judges
    /// <c>TimeEntryLockAt</c> itself on
    /// <see cref="ETimeSheet.Application.Common.EmployeeClock"/>, and a null
    /// cut-off means no lock.
    /// </para>
    /// </summary>
    public bool? CanUserLoggedPreDayTime { get; set; }

    /// <summary>
    /// The user's country - <b><c>dbo.Signup.CountryID</c></b>, added to the
    /// procedure on 2026-09-21.
    /// <para>
    /// Note whose column it is: the procedure joins <c>dbo.Signup</c> and takes
    /// the country from the <i>person</i>, while
    /// <c>dbo.TimesheetMasterSetup</c> has a <c>CountryID</c> of its own that
    /// the Admin save writes. The two can disagree, and this one is the signup's.
    /// </para>
    /// </summary>
    public int? CountryId { get; set; }

    /// <summary>
    /// The setup's IANA time zone - <c>dbo.TimesheetMasterSetup.TimeZone</c>,
    /// one id such as <c>"Asia/Kolkata"</c>. Added to the procedure on
    /// 2026-09-21 so the timesheet screen can show which clock the day's
    /// cut-off is measured on.
    /// </summary>
    public string? TimeZone { get; set; }
}

/// <summary>
/// One row of either result set returned by <c>dbo.spc_GetUsersTaskList</c>.
/// Both sets select <c>TaskID</c> and <c>Taskname</c> - the sprint set aliases
/// <c>SprintTaskID</c> to <c>TaskID</c> - so one shape serves both.
/// <para>
/// Not a keyless <c>DbSet</c> like the other procedure rows: EF Core reads only
/// the first result set of a batch, so <c>TimeLogRepository</c> reads these by
/// column name itself.
/// </para>
/// </summary>
public class UserTaskListItem
{
    public int TaskId { get; set; }

    public string? TaskName { get; set; }
}

/// <summary>
/// Both result sets of <c>dbo.spc_GetUsersTaskList</c>, kept apart in the
/// order the procedure returns them.
/// </summary>
public class UserTaskList
{
    /// <summary>The first result set - <c>dbo.TaskMaster</c>.</summary>
    public IReadOnlyList<UserTaskListItem> ProjectTasks { get; set; } =
        Array.Empty<UserTaskListItem>();

    /// <summary>The second result set - <c>dbo.SprintTaskManagement</c>.</summary>
    public IReadOnlyList<UserTaskListItem> SprintTasks { get; set; } =
        Array.Empty<UserTaskListItem>();
}

/// <summary>
/// The one row returned by <c>dbo.spc_GetUserDashboardSummaryByUserID</c>.
/// <para>
/// A keyless type, like the other procedure rows: never tracked, never
/// written, and shaped exactly like the procedure's SELECT list. Every figure
/// is computed by the procedure; none is a column on any table.
/// </para>
/// </summary>
public class UserDashboardSummaryDetail
{
    public int UserId { get; set; }

    public string? Name { get; set; }

    public DateTime WeekStartDate { get; set; }

    public DateTime WeekEndDate { get; set; }

    /// <summary>Never null: the procedure wraps the sum in <c>ISNULL(..., 0)</c>.</summary>
    public int TodayLoggedMinutes { get; set; }

    public string? TodayLoggedText { get; set; }

    /// <summary>Never null, as <see cref="TodayLoggedMinutes"/>.</summary>
    public int WeekLoggedMinutes { get; set; }

    public string? WeekLoggedText { get; set; }

    public int? WeekExpectedMinutes { get; set; }

    public string? WeekExpectedText { get; set; }

    /// <summary>A <c>DECIMAL(5, 2)</c> in the procedure.</summary>
    public decimal? WeekLoggedPercentage { get; set; }

    public int? WeekPendingMinutes { get; set; }

    public string? WeekPendingText { get; set; }
}
