/*
    THE TIMELOG MODULE'S MODEL - one file, every shape the module exchanges.

    TimeLogController and TimeLogService have exactly one model file between
    them, and this is it: the request payloads, the response payloads, and the
    rows the module's stored procedures return. Adding a shape to this module
    means adding a class HERE, not adding a file next to it.

    A module may READ another module's model - TimeLogService reads the Admin
    entity, for instance - but it never gains a second model file of its own.

    Not here, deliberately:
      - EF entities (Models/Entities/) map one-to-one to a TABLE, not to a
        controller. dbo.DayMaster belongs to no controller at all, and
        dbo.TimesheetMasterSetup is read by two of them.
      - Validators, mappings and services keep their own files; this is the
        model, not the module.

    ORDER MATTERS in the response types. System.Text.Json writes properties in
    declaration order, so moving a property up or down here changes the JSON a
    client receives. Reordering is a contract change, not a tidy-up.
*/

using ETimeSheet.Shared.Enums;

namespace ETimeSheet.Application.Models;

/// <summary>
/// Body of the time logged details request. Everything the query needs travels
/// in the payload; nothing is taken from the route or the query string.
/// <para>
/// <c>UserId</c> is supplied by the caller. It would normally be taken from the
/// authenticated principal rather than trusted from the request; authentication
/// is switched off for now, so this is deliberately temporary.
/// </para>
/// </summary>
public class TimeLoggedDetailsForTaskRequest
{
    public int UserId { get; set; }

    public int TaskId { get; set; }

    /// <summary>
    /// Inclusive lower bound on the entry's <c>StartDate</c>. A calendar date,
    /// not an instant - the column is <c>date</c>.
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>Inclusive upper bound on the entry's <c>StartDate</c>.</summary>
    public DateTime EndDate { get; set; }
}

/// <summary>
/// Body of the "log my time" request - one block of work an employee recorded
/// against one task.
/// <para>
/// This is an <b>insert only</b>. There is no sheet id, because the caller is
/// logging new time rather than correcting an entry; editing an existing one is
/// a separate operation and is not built yet.
/// </para>
/// <para>
/// <c>UserId</c> is supplied by the caller and would normally come from the
/// authenticated principal. Authentication is switched off for this project for
/// now, so it travels in the payload - deliberately temporary, exactly as on the
/// read endpoints.
/// </para>
/// </summary>
public class TimeLogSaveRequest
{
    /// <summary>The employee the time belongs to. Required - it is also what selects the timesheet setup the entry is validated against.</summary>
    public int UserId { get; set; }

    /// <summary>The task the work was done on. Required.</summary>
    public int TaskId { get; set; }

    /// <summary>What was worked on. Optional, and unbounded - the column is <c>nvarchar(max)</c>.</summary>
    public string? Description { get; set; }

    // SheetCode is deliberately NOT here. It is generated by TimeLogService on
    // insert - T0001, T0002, ... - and comes back on TimeLogResponse. A caller
    // that could supply one could collide with the sequence or skip a number,
    // and then no reader could trust the codes to mean anything.

    /// <summary>
    /// The day the work started. A calendar date - the column is <c>date</c>, so
    /// any time part is ignored.
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>
    /// The day the work ended. Optional: left out it is the same day as
    /// <see cref="StartDate"/>, which is the ordinary case. It exists for a
    /// shift that runs past midnight, which is the only reason the table carries
    /// two dates.
    /// </summary>
    public DateTime? EndDate { get; set; }

    /// <summary>
    /// Clock time the work started, as a string in <c>hh:mm:ss</c> - for example
    /// <c>"09:00:00"</c>. Required.
    /// <para>
    /// A string rather than a <c>TimeSpan</c>, as on every time input in this API:
    /// the contract is one exact format, and <c>TimeLogService</c> is what reads
    /// it. See <see cref="ETimeSheet.Shared.Utilities.TimeOfDay"/>.
    /// </para>
    /// </summary>
    public string? StartTime { get; set; }

    /// <summary>
    /// Clock time the work ended, also <c>hh:mm:ss</c>. Required, and must be
    /// after the start once both dates are taken into account.
    /// </summary>
    public string? EndTime { get; set; }

    /// <summary>
    /// <b>1 = Save, 2 = Draft.</b> Required - an entry with no status is neither
    /// saved nor drafted, and the reads would not know what to do with it.
    /// </summary>
    public TimeLogStatus Status { get; set; }

    /// <summary>
    /// The user recording the entry. Usually the same person as
    /// <see cref="UserId"/>, but not necessarily - a manager may log on someone's
    /// behalf, and the row should say who actually did it.
    /// <para>
    /// <b>Temporary</b>, as on <c>AdminSaveRequest.CreatedBy</c>: this
    /// belongs in the token, and it moves there the moment JWT is switched back
    /// on.
    /// </para>
    /// </summary>
    public int CreatedBy { get; set; }
}

/// <summary>
/// Caller-facing view of one row returned by
/// <c>spc_GetTimeLoggedDetailsForTask</c>.
/// </summary>
public class TimeLoggedDetailResponse
{
    public int SheetId { get; init; }

    public string? SheetCode { get; init; }

    public string? Description { get; init; }

    public DateTime? StartDate { get; init; }

    public TimeSpan? StartTime { get; init; }

    public DateTime? EndDate { get; init; }

    public TimeSpan? EndTime { get; init; }

    /// <summary>
    /// <b>1 = Save, 2 = Draft only</b> - see
    /// <see cref="ETimeSheet.Shared.Utilities.Constants.TimeLog.Status"/>.
    /// Serialised by name, so a caller sees "Save" or "Draft".
    /// </summary>
    public TimeLogStatus? Status { get; init; }

    /// <summary>"Save" or "Draft". Empty when the row's <c>Status</c> column is null.</summary>
    public string StatusName { get; init; } = string.Empty;

    /// <summary>Duration of this entry in hours, to two decimal places.</summary>
    public decimal? TotalWorkingHours { get; init; }

    /// <summary>Duration of this entry in whole minutes.</summary>
    public int? TotalWorkingMinutes { get; init; }
}

/// <summary>
/// Totals for the requested period. <b>All three are in hours</b>, decimal, so
/// seven and a half hours is <c>7.5</c> rather than <c>07:30:00</c>.
/// </summary>
public class TimeLoggedSummaryResponse
{
    /// <summary>Sum of the returned entries' durations.</summary>
    public decimal TotalWorkInHours { get; init; }

    /// <summary>
    /// What the user was expected to log over the period, from their
    /// <c>TimesheetMasterSetup</c> row. Zero when they have no setup.
    /// </summary>
    public decimal TotalExpected { get; init; }

    /// <summary>
    /// <see cref="TotalExpected"/> minus <see cref="TotalWorkInHours"/>.
    /// Negative when the user logged more than expected, which is information
    /// rather than an error, so it is not clamped to zero.
    /// </summary>
    public decimal TotalRemaining { get; init; }
}

/// <summary>
/// What the time logged details endpoint returns: the totals for the period,
/// then the entries they were derived from.
/// <para>
/// <b>Property order matters here.</b> System.Text.Json writes properties in
/// declaration order, so <see cref="Summary"/> is declared first to put the
/// totals at the top of the payload - where they can be read without scrolling
/// past a long <see cref="Details"/> array.
/// </para>
/// </summary>
public class TimeLoggedDetailsForTaskResponse
{
    public TimeLoggedSummaryResponse Summary { get; init; } = new();

    public IReadOnlyCollection<TimeLoggedDetailResponse> Details { get; init; } =
        Array.Empty<TimeLoggedDetailResponse>();
}

/// <summary>
/// One row of <c>dbo.TimeLog</c> as the API returns it - the entry exactly as it
/// was stored, so a caller that has just logged time can show it back without a
/// second request.
/// <para>
/// Distinct from <see cref="TimeLoggedDetailResponse"/>, which is the shape
/// <c>spc_GetTimeLoggedDetailsForTask</c> returns. They overlap but are not the
/// same thing, and tying the write response to the procedure's shape would make
/// the procedure impossible to change.
/// </para>
/// </summary>
public class TimeLogResponse
{
    /// <summary>The generated key. This is the one field the caller could not have known before the call.</summary>
    public int SheetId { get; set; }

    public string? SheetCode { get; set; }

    public int? TaskId { get; set; }

    public string? Description { get; set; }

    public int? UserId { get; set; }

    public DateTime? StartDate { get; set; }

    public TimeSpan? StartTime { get; set; }

    public DateTime? EndDate { get; set; }

    public TimeSpan? EndTime { get; set; }

    /// <summary>1 = Save, 2 = Draft.</summary>
    public TimeLogStatus? Status { get; set; }

    /// <summary>The status spelled out, so a client does not have to carry the numbers.</summary>
    public string StatusName { get; set; } = string.Empty;

    /// <summary>
    /// How long the entry covers, in hours to two places. Computed from both
    /// ends including their dates, so an overnight entry measures correctly
    /// rather than coming out negative.
    /// </summary>
    public decimal TotalWorkingHours { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreateDate { get; set; }
}

/// <summary>
/// Caller-facing view of a user's timesheet setup, as returned by
/// <c>spc_GetTimesheetMasterSetupByUserID</c>.
/// </summary>
public class TimesheetMasterSetupResponse
{
    public int SetupId { get; init; }

    /// <summary>
    /// From the <c>MaxTimeinhrs</c> column, a <c>time(7)</c>. Serialises as
    /// <c>"08:00:00"</c>, not as a number.
    /// </summary>
    public TimeSpan? MaxTimeLoggedByUserInHours { get; init; }

    /// <summary>From the <c>MaxTiminmins</c> column, a <c>time(7)</c>.</summary>
    public TimeSpan? MaxTimeLoggedByUserInMinutes { get; init; }

    public int? ContractType { get; init; }

    /// <summary>
    /// First day of the timesheet week - a <c>DayMaster.DayID</c>: 1 = Monday
    /// through 7 = Sunday. It was a two-character code until 2026-09-17.
    /// </summary>
    public int? StartDay { get; init; }

    /// <summary>Last day of the timesheet week. A <c>DayMaster.DayID</c>, as <see cref="StartDay"/>.</summary>
    public int? EndDay { get; init; }

    /// <summary>
    /// Whether the user may log time against a previous day. Held as 0 or 1 in
    /// the database and surfaced as <c>true</c>/<c>false</c>.
    /// </summary>
    public bool? CanUserLoggedPreDayTime { get; init; }
}

/// <summary>
/// One row of the result set returned by <c>dbo.spc_GetTimeLoggedDetailsForTask</c>.
/// <para>
/// This is a keyless type: it is not a table, it has no identity and it is never
/// tracked or written. It exists solely to give the procedure's SELECT list a
/// shape EF Core can materialise, which is why it carries exactly the eight
/// columns the procedure returns - no more.
/// </para>
/// </summary>
public class TimeLoggedDetail
{
    public int SheetId { get; set; }

    public string? SheetCode { get; set; }

    public string? Description { get; set; }

    public DateTime? StartDate { get; set; }

    public TimeSpan? StartTime { get; set; }

    public DateTime? EndDate { get; set; }

    public TimeSpan? EndTime { get; set; }

    /// <summary>
    /// The <c>Status</c> column as returned by the procedure.
    /// <para><b>1 = Save, 2 = Draft only</b> - see
    /// <see cref="ETimeSheet.Shared.Utilities.Constants.TimeLog.Status"/>.</para>
    /// </summary>
    public TimeLogStatus? Status { get; set; }

    /// <summary>
    /// Duration of this entry in hours, computed by the procedure and already
    /// rounded to two decimal places. <c>DATEDIFF(...)/60.0</c> yields a SQL
    /// <c>numeric</c>, hence <c>decimal</c> rather than <c>double</c>.
    /// </summary>
    public decimal? TotalWorkingHours { get; set; }

    /// <summary>
    /// Duration of this entry in whole minutes, computed by the procedure.
    /// <c>DATEDIFF</c> returns an <c>int</c>, and this is the exact value the
    /// summary totals are built from.
    /// </summary>
    public int? TotalWorkingMinutes { get; set; }
}

/// <summary>
/// One row of the result set returned by
/// <c>dbo.spc_GetTimesheetMasterSetupByUserID</c> - the limits and working-week
/// settings that apply to one user's timesheets.
/// <para>
/// This is a keyless type: it is not a table, it has no identity and it is never
/// tracked or written. It exists solely to give the procedure's SELECT list a
/// shape EF Core can materialise, which is why it carries only the six columns
/// the procedure returns. The full table is
/// <see cref="ETimeSheet.Application.Models.Entities.TimesheetMasterSetup"/>.
/// </para>
/// </summary>
public class TimesheetMasterSetupDetail
{
    public int SetupId { get; set; }

    /// <summary>
    /// The <c>MaxTimeinhrs</c> column, aliased by the procedure. A
    /// <c>time(7)</c>, not a number - so "8 hours" is stored as <c>08:00:00</c>.
    /// </summary>
    public TimeSpan? MaxTimeLoggedByUserInHours { get; set; }

    /// <summary>The <c>MaxTiminmins</c> column, aliased by the procedure. Also a <c>time(7)</c>.</summary>
    public TimeSpan? MaxTimeLoggedByUserInMinutes { get; set; }

    public int? ContractType { get; set; }

    /// <summary>
    /// First day of the timesheet week - a <c>dbo.DayMaster.DayID</c> (1 = Monday
    /// ... 7 = Sunday). The procedure selects the column straight through, so it
    /// returns whatever type the column has: an <c>int</c> since 2026-09-17.
    /// </summary>
    public int? StartDay { get; set; }

    /// <summary>Last day of the timesheet week. A <c>DayMaster.DayID</c>, as <see cref="StartDay"/>.</summary>
    public int? EndDay { get; set; }

    /// <summary>
    /// Whether the user may log time against a previous day. Stored as 0 or 1.
    /// <para>
    /// Exposed as a <c>bool?</c> rather than a number so callers get
    /// <c>true</c>/<c>false</c> instead of having to know that 1 means yes. The
    /// store type is handled in the mapping, not here.
    /// </para>
    /// </summary>
    public bool? CanUserLoggedPreDayTime { get; set; }
}
