using ETimeSheet.Application.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ETimeSheet.Infrastructure.Data.Configurations;

/// <summary>
/// Database mapping for <see cref="EmailQueue"/> onto the existing
/// <c>dbo.EmailQueue</c> table.
/// <para>
/// This is a database-first mapping: the column names and types below must
/// match <c>docs/database/schema/dbo.EmailQueue.sql</c> exactly. No index or
/// constraint is declared, because those are owned by the database.
/// </para>
/// </summary>
public class EmailQueueConfiguration : IEntityTypeConfiguration<EmailQueue>
{
    public void Configure(EntityTypeBuilder<EmailQueue> builder)
    {
        builder.ToTable("EmailQueue");

        builder.HasKey(email => email.EmailQueueId);

        // bigint IDENTITY: generated by the insert, read back after the save.
        builder.Property(email => email.EmailQueueId)
            .HasColumnName("EmailQueueID")
            .ValueGeneratedOnAdd();

        builder.Property(email => email.UserId).HasColumnName("UserID");

        builder.Property(email => email.EmailAddress)
            .HasColumnName("EmailAddress")
            .HasMaxLength(255)
            .IsUnicode(false);

        builder.Property(email => email.OrgId).HasColumnName("OrgID");

        // int here, though dbo.EmailType.EmailTypeID is tinyint.
        builder.Property(email => email.EmailTypeId).HasColumnName("EmailTypeID");

        builder.Property(email => email.EmailStatusId)
            .HasColumnName("EmailStatusID")
            .HasColumnType("tinyint");

        // Tells EF Core the column has a default, so an unset CreatedDate is
        // left out of the INSERT and GETDATE() fills it. Describes the
        // database; creates nothing.
        builder.Property(email => email.CreatedDate)
            .HasColumnName("CreatedDate")
            .HasColumnType("datetime2(0)")
            .HasDefaultValueSql("GETDATE()");

        builder.Property(email => email.SentDate)
            .HasColumnName("SentDate")
            .HasColumnType("datetime2(0)");

        builder.Property(email => email.LastAttemptDate)
            .HasColumnName("LastAttemptDate")
            .HasColumnType("datetime2(0)");

        builder.Property(email => email.AttemptCount).HasColumnName("AttemptCount");

        builder.Property(email => email.ErrorMessage)
            .HasColumnName("ErrorMessage")
            .HasMaxLength(2000)
            .IsUnicode(false);
    }
}
